name: Continuous Integration/Deployment

on: [push]

env:
  CI: true

jobs:
  ci_cd:
    name: continuous integration/deployment

    # wait for a previous job to complete
    concurrency: ${{ github.workflow}}-${{ github.ref }}

    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          persist-credentials: true

      # https://github.com/actions/setup-node
      - name: setup node version
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # https://github.com/actions/cache
      - name: cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          # include the branch name here..?
          key: node-modules-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: install node modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: lint
        run: npm run lint:all

      - name: compile
        run: npm run compile

      - name: test
        run: npm run test

      - name: fetch git tags
        run: git fetch --prune --unshallow --tags

      - name: release
        run: node scripts/release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_ACTOR: abstracter-bot <bot@abstracter.io>
          GITHUB_PAT_TOKEN: ${{ secrets.BOT_PAT }}
